name: Gulpease Index
on:
  pull_request:
    branches: 
      - main
      - 'docs/**'
jobs:
  test-gulpease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find modified LaTeX files
        id: find
        run: |
          git remote set-branches --add origin main
          git fetch
          changed_files=$(git diff --name-only origin/$GITHUB_BASE_REF | grep '.tex$') || true
          changed_document=$(echo "$changed_files" | cut -d/ -f1-3 | uniq) 
          echo "$changed_files"
          echo "$changed_document"
          echo "doc=$changed_document" >> $GITHUB_OUTPUT
      - name : Install dependencies
        run: |
          if [ -n "${{ steps.find.outputs.doc }}" ]; then
           echo ${{ steps.find.outputs.doc }}
          fi
